"""
figure4_forest.py — Figure 4: Subgroup forest plot
====================================================
Displays odds ratios (OR, 95% CI) from GEE logistic models for all five
outcomes across pre-specified subgroups (sex, age group, education level,
headache history).

Design pattern
--------------
The script is split into two sections:

  Section 1 — Computation: runs GEE models and saves results to a pickle
              cache. Skipped on subsequent runs unless the cache is deleted.
              Delete `figure4_forest_cache.pkl` to force recomputation.

  Section 2 — Plotting: reads the cache and renders the figure. Can be
              edited and re-run instantly without re-fitting the models.

Inputs : clearhead_long.csv                  (generated by analysis.py)
         data/donnees_demographique_*.csv    (demographics — not shared)
         data/QST_06*.csv                    (questionnaire data — not shared)
Outputs: ../graphs/figure4_forest.png        (300 dpi, for submission)
         ../graphs/figure4_forest.pdf        (vector, for production)

Usage:
    # Run from scripts/
    python figure4_forest.py
"""

import os
import glob
import pickle
import warnings

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.gridspec import GridSpec
import numpy as np
import pandas as pd
import scipy.stats as stats
from statsmodels.genmod.cov_struct import Exchangeable
from statsmodels.genmod.families import Binomial
from statsmodels.genmod.generalized_estimating_equations import GEE

warnings.filterwarnings('ignore')

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)
DATA_DIR   = os.path.join(ROOT_DIR, 'data')
CACHE_FILE = os.path.join(SCRIPT_DIR, 'figure4_forest_cache.pkl')

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1 — COMPUTATION
# ══════════════════════════════════════════════════════════════════════════════

if not os.path.exists(CACHE_FILE):
    print('Cache not found — running GEE models...')

    df = pd.read_csv(os.path.join(SCRIPT_DIR, 'clearhead_long.csv'))
    df['report_id'] = df['report_id'].astype(str)

    # Merge demographics
    demo = pd.read_csv(
        os.path.join(DATA_DIR, 'donnees_demographique_20260426.csv'),
        encoding='latin-1'
    )
    df = df.merge(demo[['id_unik', 'Sexe', 'age', 'diplome']], on='id_unik', how='left')

    df['age_grp'] = pd.cut(df['age'], bins=[0, 40, 55, 70, 120],
                           labels=['18–40', '41–55', '56–70', '>70'])

    def map_edu(s):
        """Map raw diploma strings to simplified categories."""
        if pd.isna(s):
            return np.nan
        s = s.strip()
        if 'Aucun' in s or 'CFG' in s or 'primaire' in s or 'brevet' in s.lower() or 'BEPC' in s:
            return 'No diploma / primary'
        if 'CAP' in s or 'BEP' in s or 'Autre' in s:
            return 'CAP / BEP'
        if 'Baccalauréat' in s or 'baccalauréat' in s:
            return 'Baccalauréat'
        if ('Bac+2' in s or 'DUT' in s or 'BTS' in s or 'DEUG' in s or 'sanitaires' in s
                or 'licence' in s.lower() or 'master' in s.lower()
                or 'doctorat' in s.lower() or 'grande' in s.lower()
                or 'DEA' in s or 'DESS' in s or 'maîtrise' in s):
            return 'Bac+ or above'
        return np.nan

    df['edu'] = df['diplome'].apply(map_edu)
    df['edu2'] = df['edu'].apply(
        lambda x: 'College degree or above' if x == 'Bac+ or above'
                  else ('High school diploma or less' if pd.notna(x) else np.nan)
    )
    edu_order = ['High school diploma or less', 'College degree or above']

    # Merge headache history from questionnaire files
    qst_files = sorted(
        glob.glob(os.path.join(DATA_DIR, 'QST_0661_20260426.csv')) +
        glob.glob(os.path.join(DATA_DIR, 'qst_066[2-8]_20260426.csv'))
    )
    maux = pd.concat([
        pd.read_csv(f, encoding='latin-1', usecols=['id_unik', 'Maux_tete'])
        for f in qst_files
    ]).drop_duplicates('id_unik')
    maux['headache_hx'] = maux['Maux_tete'].map({1: 'Yes', 2: 'No'})
    df = df.merge(maux[['id_unik', 'headache_hx']], on='id_unik', how='left')

    df['arm_bin'] = (df['arm'] == 'intervention').astype(float)

    # Binarise Likert outcomes at ≥ 4 (as pre-registered for the forest plot)
    df['Q2_bin4'] = (df['Q2_num'] >= 4).astype(float)
    df['Q4_bin4'] = (df['Q4_num'] >= 4).astype(float)
    df['Q5_bin4'] = (df['Q5_num'] >= 4).astype(float)

    outcomes_cfg = [
        ('Q1_correct', 'Objective\ncomprehension'),
        ('Q2_bin4',    'Satisfaction'),
        ('Q4_bin4',    'Subjective\ncomprehension'),
        ('Q5_bin4',    'Anxiety'),
        ('Q3_bin',     'Willingness\nto consult'),
    ]

    subgroups_cfg = [
        ('Overall',          None,           [('Overall', df)]),
        ('Sex',              'Sexe',         [('Female', df[df['Sexe'] == 'F']),
                                              ('Male',   df[df['Sexe'] == 'M'])]),
        ('Age group',        'age_grp',      [(g, df[df['age_grp'] == g])
                                              for g in ['18–40', '41–55', '56–70', '>70']]),
        ('Education',        'edu2',         [(g, df[df['edu2'] == g]) for g in edu_order]),
        ('Headache history', 'headache_hx',  [('Yes', df[df['headache_hx'] == 'Yes']),
                                              ('No',  df[df['headache_hx'] == 'No'])]),
    ]

    def gee_result(df_sub, outcome):
        """Fit a GEE logistic model and return OR with 95% CI, or None on failure."""
        d = df_sub.dropna(subset=[outcome]).sort_values('id_unik').reset_index(drop=True)
        if d['id_unik'].nunique() < 20:
            return None
        n_rep   = d['report_id'].nunique()
        formula = (f'{outcome} ~ arm_bin + C(report_id)' if n_rep > 1
                   else f'{outcome} ~ arm_bin')
        try:
            res  = GEE.from_formula(formula, groups='id_unik', data=d,
                                    family=Binomial(), cov_struct=Exchangeable()).fit()
            ci   = res.conf_int()
            coef = res.params['arm_bin']
            lo   = ci.loc['arm_bin', 0]
            hi   = ci.loc['arm_bin', 1]
            return dict(
                est    = np.exp(coef),
                lo     = np.exp(lo),
                hi     = np.exp(hi),
                n_ctrl = d[d['arm'] == 'control']['id_unik'].nunique(),
                n_intv = d[d['arm'] == 'intervention']['id_unik'].nunique(),
            )
        except Exception:
            return None

    def p_interaction(svar, outcome):
        """Return the Wald p-value for the arm × subgroup interaction term."""
        d = df.dropna(subset=[outcome, svar]).sort_values('id_unik').reset_index(drop=True)
        try:
            res   = GEE.from_formula(
                f'{outcome} ~ arm_bin * C({svar}) + C(report_id)',
                groups='id_unik', data=d,
                family=Binomial(), cov_struct=Exchangeable()
            ).fit()
            terms = [c for c in res.params.index if 'arm_bin:' in c]
            if not terms:
                return np.nan
            idx   = [list(res.params.index).index(t) for t in terms]
            coefs = res.params.values[idx]
            cov   = res.cov_params().values[np.ix_(idx, idx)]
            W     = coefs @ np.linalg.inv(cov) @ coefs
            return 1 - stats.chi2.cdf(W, len(idx))
        except Exception:
            return np.nan

    # Compute interaction p-values
    raw_inter = {}
    for grp_label, svar, levels in subgroups_cfg:
        if svar:
            for outcome, _ in outcomes_cfg:
                print(f'  interaction: {grp_label} × {outcome}...')
                raw_inter[(grp_label, outcome)] = p_interaction(svar, outcome)

    # Build rows for the plot
    plot_rows = []
    for grp_label, svar, levels in subgroups_cfg:
        inter = ({o: raw_inter.get((grp_label, o), np.nan) for o, _ in outcomes_cfg}
                 if svar else {})
        if grp_label != 'Overall':
            plot_rows.append(('header', grp_label, inter))
        for lbl, df_sub in levels:
            res_by_outcome = {o: gee_result(df_sub, o) for o, _ in outcomes_cfg}
            plot_rows.append(('sub', lbl, res_by_outcome))

    cache = dict(plot_rows=plot_rows, outcomes_cfg=outcomes_cfg)
    with open(CACHE_FILE, 'wb') as fh:
        pickle.dump(cache, fh)
    print(f'Results cached to {CACHE_FILE}')

else:
    print(f'Loading cached results from {CACHE_FILE}')
    with open(CACHE_FILE, 'rb') as fh:
        cache = pickle.load(fh)
    plot_rows    = cache['plot_rows']
    outcomes_cfg = cache['outcomes_cfg']

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2 — PLOTTING
# ══════════════════════════════════════════════════════════════════════════════

plt.rcParams.update({
    'font.family':  'Nimbus Sans',
    'font.size':    8,
    'pdf.fonttype': 42,   # embed fonts (required by Nature)
    'ps.fonttype':  42,
})

DARK = '#1a1a1a'
GREY = '#777777'

ROW_H = 0.22
HDR_H = 0.18

n_outcomes   = len(outcomes_cfg)
total_h_data = sum(HDR_H if r[0] == 'header' else ROW_H for r in plot_rows)
TOP_PAD      = 0.90
BOT_PAD      = 0.50
fig_h        = total_h_data + TOP_PAD + BOT_PAD

# Column widths (in inches)
LABEL_W = 1.80   # subgroup label column (wide enough to avoid overlap)
N_W     = 1.05   # control / intervention n columns
PANEL_W = 1.80   # width per outcome panel
fig_w   = LABEL_W + N_W + n_outcomes * PANEL_W + 0.15

# Shared log-scale limits derived from the data
all_vals = []
for rtype, _, data in plot_rows:
    if rtype == 'sub':
        for outcome, _ in outcomes_cfg:
            r = data.get(outcome)
            if r:
                all_vals.extend([r['lo'], r['hi']])
lo_all  = min(all_vals)
hi_all  = max(all_vals)
log_ext = max(abs(np.log(lo_all)), abs(np.log(hi_all))) * 1.12
X_MIN   = np.exp(-log_ext)
X_MAX   = np.exp( log_ext)

fig = plt.figure(figsize=(fig_w, fig_h), facecolor='white')

gs = GridSpec(
    1, n_outcomes,
    left   = (LABEL_W + N_W) / fig_w,
    right  = (LABEL_W + N_W + n_outcomes * PANEL_W) / fig_w,
    bottom = BOT_PAD / fig_h,
    top    = (BOT_PAD + total_h_data) / fig_h,
    wspace = 0,
)
axes = [fig.add_subplot(gs[0, i], facecolor='white') for i in range(n_outcomes)]

# Precompute y positions for each row
y_positions = []
yy = 0
for rtype, *_ in plot_rows:
    h = HDR_H if rtype == 'header' else ROW_H
    y_positions.append(yy + h / 2)
    yy += h

nice_ticks  = [0.25, 0.5, 1.0, 2.0, 4.0]
panel_ticks = [t for t in nice_ticks if X_MIN <= t <= X_MAX]

for col_i, (outcome, title) in enumerate(outcomes_cfg):
    ax = axes[col_i]
    ax.set_xscale('log')
    ax.set_xlim(X_MIN, X_MAX)
    ax.set_ylim(0, total_h_data)
    ax.invert_yaxis()
    ax.set_facecolor('white')
    ax.axvline(1.0, color='#555555', lw=0.8, ls='--', zorder=1)
    ax.set_xticks(panel_ticks)
    ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{x:g}'))
    ax.tick_params(axis='x', labelsize=7.5, length=3, width=0.7, pad=2)
    ax.set_xlabel('Odds ratio', fontsize=7, labelpad=3)
    ax.set_title(title, fontsize=8, fontweight='bold', pad=5, color=DARK)
    for sp in ax.spines.values():
        sp.set_visible(False)
    ax.tick_params(axis='y', left=False, labelleft=False)

    # Light vertical grid at tick marks
    for xv in panel_ticks:
        ax.axvline(xv, color='#eeeeee', lw=0.5, zorder=0)

    for i, (rtype, label, data) in enumerate(plot_rows):
        yc = y_positions[i]
        if rtype == 'header':
            pint = data.get(outcome, np.nan) if data else np.nan
            if not np.isnan(pint):
                ps   = '<0.001' if pint < 0.001 else f'{pint:.3f}'
                pcol = DARK if pint < 0.05 else '#999999'
                ax.text(0.5, yc, f'P interaction = {ps}',
                        ha='center', va='center', fontsize=5.5,
                        color=pcol, style='italic',
                        transform=ax.get_yaxis_transform(),
                        bbox=dict(facecolor='white', edgecolor='none', pad=1.5))
            continue
        if rtype != 'sub':
            continue
        r = data.get(outcome)
        if r is None:
            continue
        est  = np.clip(r['est'], X_MIN * 1.001, X_MAX * 0.999)
        lo_c = np.clip(r['lo'],  X_MIN * 1.001, X_MAX * 0.999)
        hi_c = np.clip(r['hi'],  X_MIN * 1.001, X_MAX * 0.999)

        # Confidence interval line with caps
        ax.plot([lo_c, hi_c], [yc, yc], color=DARK, lw=0.9, zorder=2)
        for xv in [lo_c, hi_c]:
            ax.plot([xv, xv], [yc - 0.05, yc + 0.05], color=DARK, lw=0.9, zorder=2)

        # Point estimate: diamond for Overall, square for subgroups
        if label == 'Overall':
            dw = log_ext * 0.030
            dx = [np.exp(np.log(est) - dw), est, np.exp(np.log(est) + dw), est,
                  np.exp(np.log(est) - dw)]
            dy = [yc, yc - 0.055, yc, yc + 0.055, yc]
            ax.fill(dx, dy, color=DARK, zorder=3)
        else:
            ax.plot(est, yc, 's', color=DARK, ms=4, zorder=3, markeredgewidth=0)

# ── Left-side labels and n columns ───────────────────────────────────────────

def fy(yc):
    """Convert data y-coordinate to figure fraction."""
    ax_bot = BOT_PAD / fig_h
    ax_top = (BOT_PAD + total_h_data) / fig_h
    return ax_bot + (1.0 - yc / total_h_data) * (ax_top - ax_bot)


X_LABEL = 0.005
X_N     = (LABEL_W + N_W * 0.22) / fig_w
X_N2    = (LABEL_W + N_W * 0.78) / fig_w

top_y = (BOT_PAD + total_h_data) / fig_h + 0.008
fig.text(X_LABEL, top_y, 'Subgroup', ha='left', va='bottom',
         fontsize=8, fontweight='bold', color=DARK)
fig.text(X_N,  top_y, 'Control\n(n)',      ha='center', va='bottom',
         fontsize=7.5, fontweight='bold', color=DARK)
fig.text(X_N2, top_y, 'Intervention\n(n)', ha='center', va='bottom',
         fontsize=7.5, fontweight='bold', color=DARK)

# Horizontal separator lines with white gaps at panel boundaries
GAP              = 0.008
panel_boundaries = [(LABEL_W + N_W + col_i * PANEL_W) / fig_w
                    for col_i in range(n_outcomes + 1)]
sep_top = (BOT_PAD + total_h_data) / fig_h
sep_bot = BOT_PAD / fig_h

seg_starts = [0.005] + [x + GAP for x in panel_boundaries[1:n_outcomes]]
seg_ends   = [x - GAP for x in panel_boundaries[1:n_outcomes]] + [0.995]

for yf in [sep_top, sep_bot]:
    for xs, xe in zip(seg_starts, seg_ends):
        fig.add_artist(plt.Line2D([xs, xe], [yf, yf],
                       transform=fig.transFigure, color='#444444', lw=0.7))

# Education label mapping (translate French categories for international readership)
EDU_LABELS = {
    'No diploma / primary': 'Less than high school',
    'CAP / BEP':            'Vocational certificate',
    'Baccalauréat':         'High school diploma',
    'Bac+ or above':        'College degree or above',
}

for i, (rtype, label, data) in enumerate(plot_rows):
    yc  = y_positions[i]
    fyc = fy(yc)

    if rtype == 'header':
        fig.text(X_LABEL, fyc, label, ha='left', va='center',
                 fontsize=8, fontweight='bold', color=DARK)
    else:
        display_label = EDU_LABELS.get(label, label)
        indent = '   ' if label != 'Overall' else ''
        fw     = 'bold' if label == 'Overall' else 'normal'
        fig.text(X_LABEL, fyc, indent + display_label, ha='left', va='center',
                 fontsize=8 if label == 'Overall' else 7.5, fontweight=fw, color=DARK)

        # n per arm (taken from the first available outcome result for this row)
        n_ctrl = n_intv = None
        for outcome, _ in outcomes_cfg:
            r = data.get(outcome)
            if r:
                n_ctrl, n_intv = r['n_ctrl'], r['n_intv']
                break
        if n_ctrl is not None:
            fig.text(X_N,  fyc, f'{n_ctrl:,}',  ha='center', va='center',
                     fontsize=7.5, color='#444444')
            fig.text(X_N2, fyc, f'{n_intv:,}', ha='center', va='center',
                     fontsize=7.5, color='#444444')

# ── Save ──────────────────────────────────────────────────────────────────────
graphs_dir = os.path.join(ROOT_DIR, 'graphs')
os.makedirs(graphs_dir, exist_ok=True)
fig.savefig(os.path.join(graphs_dir, 'figure4_forest.png'),
            dpi=300, bbox_inches='tight', pad_inches=0.15)
fig.savefig(os.path.join(graphs_dir, 'figure4_forest.pdf'),
            bbox_inches='tight', pad_inches=0.15)
print('Saved: graphs/figure4_forest.png and .pdf')
