"""
figure3_likert.py — Figure 3: Secondary patient-reported outcomes
=================================================================
Displays stacked diverging bar charts for:
  Panel A : Normal/abnormal classification (correct vs. incorrect)
  Panel B : Overall satisfaction (Likert 1–5)
  Panel C : Subjective comprehension (Likert 1–5)
  Panel D : Anxiety (Likert 1–5)
  Panel E : Willingness to contact a healthcare professional (Yes/No)

Input  : clearhead_long.csv  (generated by analysis.py)
Outputs: ../graphs/figure3_likert.png  (300 dpi, for submission)
         ../graphs/figure3_likert.pdf  (vector, for production)

Usage:
    # Run from scripts/
    python figure3_likert.py
"""

import os
import warnings

import matplotlib
matplotlib.use('Agg')
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)

# ── Load data ─────────────────────────────────────────────────────────────────
df = pd.read_csv(os.path.join(SCRIPT_DIR, 'clearhead_long.csv'))
df['arm_bin'] = (df['arm'] == 'intervention').astype(float)

# Report type mapping (established by consensus of four neuroradiologists)
gt_type = {
    '87142013': 'normal',     '91182589': 'causal',
    '88811727': 'incidental', '88096936': 'causal',
    '87381313': 'incidental', '87236611': 'normal',
}
df['report_type'] = df['report_id'].astype(str).map(gt_type)

# ── Style ─────────────────────────────────────────────────────────────────────
plt.rcParams.update({
    'font.family':       'Nimbus Sans',
    'font.size':         7,
    'axes.linewidth':    0.8,
    'axes.spines.top':   False,
    'axes.spines.right': False,
    'axes.spines.left':  False,
    'xtick.major.width': 0.8,
    'ytick.major.width': 0.8,
    'xtick.major.size':  3,
    'ytick.major.size':  0,
    'pdf.fonttype':      42,   # embed fonts as Type 1 / TrueType (required by Nature)
    'ps.fonttype':       42,
})

GREY      = '#888888'
ARMS      = ['intervention', 'control']
ARM_LBLS  = ['Intervention', 'Control']

# Diverging Likert palette (blue → grey → red)
COLORS_5 = ['#2166ac', '#92c5de', '#d1d1d1', '#f4a582', '#d6604d']
LEVELS_5 = [1, 2, 3, 4, 5]

# Binary outcome palette
COL_YES    = '#F39C12'   # amber  — Yes (willingness to consult)
COL_NO     = '#7F8C8D'   # grey   — No

# Panel A palette
COL_CORR   = '#27AE60'   # green      — correct classification
COL_INCORR = '#BDC3C7'   # light grey — incorrect classification

# ── Outcome configuration ─────────────────────────────────────────────────────
# Each tuple: (column, panel label, OR string, p-value string, is_binary)
# OR values are retrieved from the pre-fitted GEE models (analysis.py).
outcomes = [
    ('Q2_num', 'Satisfaction',             'OR = 3.26 [2.93; 3.64]', 'p < 0.001', False),
    ('Q4_num', 'Subjective comprehension', 'OR = 3.17 [2.82; 3.56]', 'p < 0.001', False),
    ('Q5_num', 'Anxiety',                  'OR = 0.92 [0.85; 0.99]', 'p = 0.037', False),
    ('Q3_bin', 'Willingness to consult',   'OR = 0.48 [0.43; 0.53]', 'p < 0.001', True),
]

# ── Helper functions ──────────────────────────────────────────────────────────

def likert_pcts(series):
    """Return list of % for each Likert level 1–5."""
    counts = series.value_counts()
    total  = counts.sum()
    return [counts.get(l, 0) / total * 100 for l in LEVELS_5]


def diverging_starts(pcts):
    """Return left-edge x-positions for a diverging stacked bar.

    Levels 1–2 extend left of zero; level 3 is split about zero;
    levels 4–5 extend right of zero.
    """
    p1, p2, p3, p4, p5 = pcts
    left_anchor = -(p1 + p2 + p3 / 2)
    return [
        left_anchor,
        left_anchor + p1,
        left_anchor + p1 + p2,
        p3 / 2,
        p3 / 2 + p4,
    ]

# ── Layout ────────────────────────────────────────────────────────────────────
# 9-row GridSpec: rows 0,2,4,6,8 hold panels A–E;
# rows 1,3,5,7 are spacers of varying height.
fig = plt.figure(figsize=(7.2, 7.8))
gs  = gridspec.GridSpec(
    9, 1, figure=fig,
    height_ratios=[10, 12, 10, 4, 10, 4, 10, 12, 10],
    left=0.22, right=0.72,
    top=0.97, bottom=0.08,
    hspace=0.0
)

ax_anom  = fig.add_subplot(gs[0])
axes_pr  = [fig.add_subplot(gs[i]) for i in [2, 4, 6, 8]]

# ── Panel A: Normal/abnormal classification ───────────────────────────────────
c_series      = df[df['arm'] == 'control']['anomalie_correct'].dropna()
pct_ctrl_corr = (c_series == 1).sum() / c_series.notna().sum() * 100

i_series      = df[df['arm'] == 'intervention']['anomalie_correct'].dropna()
pct_intv_corr = (i_series == 1).sum() / i_series.notna().sum() * 100

for y_pos, pct_corr in [(0, pct_intv_corr), (1, pct_ctrl_corr)]:
    pct_incorr = 100 - pct_corr
    ax_anom.barh(y_pos, pct_corr,   color=COL_CORR,   height=0.5, left=0, alpha=0.85)
    ax_anom.barh(y_pos, pct_incorr, color=COL_INCORR, height=0.5, left=pct_corr)
    for pct, left_e, txt_clr in [(pct_corr, 0, 'white'), (pct_incorr, pct_corr, '#444444')]:
        cx = left_e + pct / 2
        if pct > 8:
            ax_anom.text(cx, y_pos, f'{pct:.0f}%',
                         ha='center', va='center', fontsize=6,
                         color=txt_clr, fontweight='bold')

ax_anom.set_xlim(0, 100)
ax_anom.set_xticks([0, 25, 50, 75, 100])
ax_anom.set_xticklabels(['0', '25', '50', '75', '100'], fontsize=6.5)
ax_anom.set_ylim(-0.75, 1.75)
ax_anom.set_yticks([0, 1])
ax_anom.set_yticklabels(ARM_LBLS, fontsize=7)
ax_anom.tick_params(left=False)
ax_anom.tick_params(axis='x', which='both', length=3)
ax_anom.set_xlabel('Participants (%)', fontsize=6.5)

ax_anom.text(-0.30, 0.5, 'Normal/abnormal\nclassification',
             transform=ax_anom.transAxes,
             ha='right', va='center', fontsize=7.5, fontweight='bold', color='#222222')

ax_anom.text(1.04, 0.65, 'OR = 1.02 [0.92–1.14]',
             transform=ax_anom.transAxes,
             ha='left', va='center', fontsize=6.5, color='#333333')
ax_anom.text(1.04, 0.25, 'p = 0.67',
             transform=ax_anom.transAxes,
             ha='left', va='center', fontsize=6.5, color=GREY)

ax_anom.text(-0.30, 1.18, 'A', transform=ax_anom.transAxes,
             fontsize=9, fontweight='bold', va='top', ha='left')

# Panel A legend
anom_patches = [mpatches.Patch(color=COL_CORR,   label='Correct'),
                mpatches.Patch(color=COL_INCORR, label='Incorrect')]
ax_anom.legend(handles=anom_patches, loc='upper center',
               bbox_to_anchor=(0.5, -0.55), ncol=2, fontsize=6.5,
               frameon=False, handlelength=0.8,
               handletextpad=0.3, columnspacing=0.6,
               title='Classification:', title_fontsize=6.5)

# ── Panels B–E: patient-reported outcomes ─────────────────────────────────────
for ax_i, (col, label, stat_str, p_str, is_binary) in enumerate(outcomes):
    ax = axes_pr[ax_i]

    for arm_i, (arm, arm_lbl) in enumerate(zip(ARMS, ARM_LBLS)):
        series = df[df['arm'] == arm][col].dropna()
        y      = arm_i

        if is_binary:
            pct_yes = (series == 1).sum() / series.notna().sum() * 100
            pct_no  = 100 - pct_yes
            ax.barh(y, pct_yes, color=COL_YES, height=0.5, left=0)
            ax.barh(y, pct_no,  color=COL_NO,  height=0.5, left=pct_yes)
            for pct, left_edge, clr in [(pct_yes, 0, 'white'), (pct_no, pct_yes, 'white')]:
                cx = left_edge + pct / 2
                if pct > 6:
                    ax.text(cx, y, f'{pct:.0f}%',
                            ha='center', va='center', fontsize=6,
                            color=clr, fontweight='bold')
        else:
            pcts   = likert_pcts(series)
            starts = diverging_starts(pcts)
            for pct, left_edge, clr in zip(pcts, starts, COLORS_5):
                ax.barh(y, pct, color=clr, height=0.5, left=left_edge)
                vis_left  = max(-100.0, left_edge)
                vis_right = min(100.0,  left_edge + pct)
                vis_width = vis_right - vis_left
                cx        = (vis_left + vis_right) / 2
                if vis_width <= 1 or pct < 1:
                    pass
                elif vis_width >= 5:
                    ax.text(cx, y, f'{pct:.0f}%',
                            ha='center', va='center', fontsize=5.5,
                            color='white', fontweight='bold')
                else:
                    ax.plot([cx, cx], [y + 0.26, y + 0.34], color=clr, lw=0.7)
                    ax.text(cx, y + 0.38, f'{pct:.0f}%',
                            ha='center', va='bottom', fontsize=6,
                            color=clr, fontweight='bold')

    if is_binary:
        ax.set_xlim(0, 100)
        ax.set_xticks([0, 25, 50, 75, 100])
        ax.set_xticklabels(['0', '25', '50', '75', '100'], fontsize=6.5)
    else:
        ax.axvline(0, color='#aaaaaa', lw=0.7, zorder=0)
        ax.set_xlim(-100, 100)
        ax.set_xticks([-100, -75, -50, -25, 0, 25, 50, 75, 100])
        ax.set_xticklabels(['-100', '-75', '-50', '-25', '0', '25', '50', '75', '100'],
                           fontsize=6.5)

    ax.set_ylim(-0.75, 1.75)
    ax.set_yticks([0, 1])
    ax.set_yticklabels(ARM_LBLS, fontsize=7)
    ax.tick_params(left=False)
    ax.tick_params(axis='x', which='both', length=3)
    ax.set_xlabel('Participants (%)', fontsize=6.5)

    ax.text(-0.30, 0.5, label, transform=ax.transAxes,
            ha='right', va='center', fontsize=7.5, fontweight='bold', color='#222222')

    ax.text(1.04, 0.65, stat_str, transform=ax.transAxes,
            ha='left', va='center', fontsize=6.5, color='#333333')
    p_val   = float(p_str.split('=')[1].strip()) if 'p =' in p_str else 0
    p_color = '#c0392b' if ('p <' in p_str or p_val < 0.05) else GREY
    ax.text(1.04, 0.25, p_str, transform=ax.transAxes,
            ha='left', va='center', fontsize=6.5, color=p_color)

    ax.text(-0.30, 1.18, chr(ord('B') + ax_i), transform=ax.transAxes,
            fontsize=9, fontweight='bold', va='top', ha='left')

# Likert legend (below panel D = axes_pr[2])
likert_patches = [mpatches.Patch(color=c, label=str(l))
                  for c, l in zip(COLORS_5, LEVELS_5)]
axes_pr[2].legend(handles=likert_patches, loc='upper center',
                  bbox_to_anchor=(0.5, -0.55), ncol=5, fontsize=6.5,
                  frameon=False, handlelength=0.8,
                  handletextpad=0.3, columnspacing=0.6,
                  title='Likert scale (1–5):', title_fontsize=6.5)

# Binary legend (below panel E = axes_pr[3])
binary_patches = [mpatches.Patch(color=COL_YES, label='Yes'),
                  mpatches.Patch(color=COL_NO,  label='No')]
axes_pr[3].legend(handles=binary_patches, loc='upper center',
                  bbox_to_anchor=(0.5, -0.55), ncol=2, fontsize=6.5,
                  frameon=False, handlelength=0.8,
                  handletextpad=0.3, columnspacing=0.6,
                  title='Willingness to consult:', title_fontsize=6.5)

# ── Save ──────────────────────────────────────────────────────────────────────
graphs_dir = os.path.join(ROOT_DIR, 'graphs')
os.makedirs(graphs_dir, exist_ok=True)
fig.savefig(os.path.join(graphs_dir, 'figure3_likert.png'),
            dpi=300, bbox_inches='tight', pad_inches=0.1)
fig.savefig(os.path.join(graphs_dir, 'figure3_likert.pdf'),
            bbox_inches='tight', pad_inches=0.1)
print('Saved: graphs/figure3_likert.png and .pdf')
