"""
figure2_primary.py — Figure 2: Primary outcome bar chart
=========================================================
Displays the correct classification rate (Q1_correct) by arm (control vs.
intervention) for the overall population and stratified by report type
(Normal, Causal, Incidental).

Input  : clearhead_long.csv  (generated by analysis.py)
Outputs: ../graphs/figure2_primary.png  (300 dpi, for submission)
         ../graphs/figure2_primary.pdf  (vector, for production)

Usage:
    # Run from scripts/
    python figure2_primary.py
"""

import os
import warnings

import matplotlib
matplotlib.use('Agg')
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from statsmodels.stats.proportion import proportion_confint

warnings.filterwarnings('ignore')

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR   = os.path.dirname(SCRIPT_DIR)

# ── Load data ─────────────────────────────────────────────────────────────────
df = pd.read_csv(os.path.join(SCRIPT_DIR, 'clearhead_long.csv'))
df['report_type'] = np.where(df['normal'] == 1, 'Normal',
                    np.where(df['causal'] == 1, 'Causal', 'Incidental'))

# ── Compute proportions with Wilson 95% CIs ───────────────────────────────────
rows = []
for subset_label, mask in [
    ('Overall',    pd.Series([True] * len(df), index=df.index)),
    ('Normal',     df['report_type'] == 'Normal'),
    ('Causal',     df['report_type'] == 'Causal'),
    ('Incidental', df['report_type'] == 'Incidental'),
]:
    for arm in ['control', 'intervention']:
        sub  = df[mask & (df['arm'] == arm)]['Q1_correct'].dropna()
        n    = len(sub)
        k    = sub.sum()
        lo, hi = proportion_confint(k, n, method='wilson')
        rows.append(dict(subset=subset_label, arm=arm,
                         mean=k / n, lo=lo, hi=hi, n=int(n)))
res = pd.DataFrame(rows)

# ── Style ─────────────────────────────────────────────────────────────────────
plt.rcParams.update({
    'font.family':       'Nimbus Sans',
    'font.size':         7,
    'axes.linewidth':    0.8,
    'axes.spines.top':   False,
    'axes.spines.right': False,
    'xtick.major.width': 0.8,
    'ytick.major.width': 0.8,
    'xtick.major.size':  3,
    'ytick.major.size':  3,
    'xtick.direction':   'out',
    'ytick.direction':   'out',
    'pdf.fonttype':      42,   # embed fonts as Type 1 / TrueType (required by Nature)
    'ps.fonttype':       42,
})

COL_CTRL = '#4878CF'   # blue  — control arm
COL_INTV = '#D65F5F'   # red   — intervention arm
GREY     = '#888888'

BAR_W  = 0.32
OFFSET = 0.22

# ── Layout: panel A (Overall) + panel B (3 report types) ─────────────────────
fig = plt.figure(figsize=(7.2, 2.8))
gs  = fig.add_gridspec(1, 2, width_ratios=[1, 2.8],
                       left=0.09, right=0.97, top=0.88, bottom=0.22,
                       wspace=0.45)

# ── Panel A: Overall ──────────────────────────────────────────────────────────
ax_a = fig.add_subplot(gs[0])
ax_a.text(-0.22, 1.12, 'A', transform=ax_a.transAxes,
          fontsize=9, fontweight='bold', va='top', ha='left')

sub_ctrl = res[(res['subset'] == 'Overall') & (res['arm'] == 'control')].iloc[0]
sub_intv = res[(res['subset'] == 'Overall') & (res['arm'] == 'intervention')].iloc[0]
x_ctrl, x_intv = 1 - OFFSET, 1 + OFFSET

for xpos, row, color in [(x_ctrl, sub_ctrl, COL_CTRL),
                          (x_intv, sub_intv, COL_INTV)]:
    ax_a.bar(xpos, row['mean'], width=BAR_W, color=color,
             alpha=0.85, zorder=3, linewidth=0)
    ax_a.errorbar(xpos, row['mean'],
                  yerr=[[row['mean'] - row['lo']], [row['hi'] - row['mean']]],
                  fmt='none', color='#333333', capsize=2.5,
                  capthick=0.8, elinewidth=0.8, zorder=4)

y_top = max(sub_ctrl['hi'], sub_intv['hi']) + 0.04
ax_a.plot([x_ctrl, x_ctrl, x_intv, x_intv],
          [y_top - 0.01, y_top, y_top, y_top - 0.01], color=GREY, lw=0.7)
ax_a.text((x_ctrl + x_intv) / 2, y_top + 0.01, 'p = 0.54',
          ha='center', va='bottom', fontsize=6, color=GREY)
ax_a.text(x_ctrl, -0.04, f'n={sub_ctrl["n"]:,}',
          ha='center', va='top', fontsize=5.5, color=GREY)
ax_a.text(x_intv, -0.04, f'n={sub_intv["n"]:,}',
          ha='center', va='top', fontsize=5.5, color=GREY)

ax_a.set_xlim(0.45, 1.55)
ax_a.set_ylim(0, 1.05)
ax_a.set_xticks([])
ax_a.set_yticks([0, 0.25, 0.50, 0.75, 1.0])
ax_a.set_yticklabels(['0', '25', '50', '75', '100'], fontsize=6.5)
ax_a.yaxis.set_tick_params(length=3)
ax_a.set_ylabel('Correct classification (%)', fontsize=7)
ax_a.text(1.0, -0.12, 'Overall', ha='center', va='top',
          transform=ax_a.transData, fontsize=7, color='#222222')

# ── Panel B: 3 report types ───────────────────────────────────────────────────
ax_b = fig.add_subplot(gs[1])
ax_b.text(-0.10, 1.12, 'B', transform=ax_b.transAxes,
          fontsize=9, fontweight='bold', va='top', ha='left')

report_types = ['Normal', 'Causal', 'Incidental']
type_labels  = ['Normal reports', 'Causal reports', 'Incidental reports']
pval_strs_b  = ['p = 0.001', 'p < 0.001', 'p = 0.05']
centres      = [1.0, 2.2, 3.4]

for cx, subset, label, pval_str in zip(centres, report_types, type_labels, pval_strs_b):
    x_ctrl = cx - OFFSET
    x_intv = cx + OFFSET
    sub_ctrl = res[(res['subset'] == subset) & (res['arm'] == 'control')].iloc[0]
    sub_intv = res[(res['subset'] == subset) & (res['arm'] == 'intervention')].iloc[0]

    for xpos, row, color in [(x_ctrl, sub_ctrl, COL_CTRL),
                              (x_intv, sub_intv, COL_INTV)]:
        ax_b.bar(xpos, row['mean'], width=BAR_W, color=color,
                 alpha=0.85, zorder=3, linewidth=0)
        ax_b.errorbar(xpos, row['mean'],
                      yerr=[[row['mean'] - row['lo']], [row['hi'] - row['mean']]],
                      fmt='none', color='#333333', capsize=2.5,
                      capthick=0.8, elinewidth=0.8, zorder=4)

    y_top = max(sub_ctrl['hi'], sub_intv['hi']) + 0.04
    ax_b.plot([x_ctrl, x_ctrl, x_intv, x_intv],
              [y_top - 0.01, y_top, y_top, y_top - 0.01], color=GREY, lw=0.7)
    ax_b.text((x_ctrl + x_intv) / 2, y_top + 0.01, pval_str,
              ha='center', va='bottom', fontsize=6, color=GREY)
    ax_b.text(x_ctrl, -0.04, f'n={sub_ctrl["n"]:,}',
              ha='center', va='top', fontsize=5.5, color=GREY)
    ax_b.text(x_intv, -0.04, f'n={sub_intv["n"]:,}',
              ha='center', va='top', fontsize=5.5, color=GREY)
    ax_b.text(cx, -0.12, label, ha='center', va='top',
              transform=ax_b.transData, fontsize=7, color='#222222')

ax_b.set_xlim(0.45, 3.85)
ax_b.set_ylim(0, 1.05)
ax_b.set_xticks([])
ax_b.set_yticks([0, 0.25, 0.50, 0.75, 1.0])
ax_b.set_yticklabels(['0', '25', '50', '75', '100'], fontsize=6.5)
ax_b.yaxis.set_tick_params(length=3)
ax_b.set_ylabel('Correct classification (%)', fontsize=7)

for x_sep in [1.6, 2.8]:
    ax_b.axvline(x_sep, color='#e0e0e0', lw=0.6, zorder=0)

# ── Shared legend ─────────────────────────────────────────────────────────────
legend_elements = [
    mpatches.Patch(color=COL_CTRL, alpha=0.85, label='Control'),
    mpatches.Patch(color=COL_INTV, alpha=0.85, label='Intervention'),
]
fig.legend(handles=legend_elements, loc='lower center',
           ncol=2, fontsize=7, frameon=False,
           bbox_to_anchor=(0.53, -0.04),
           handlelength=1.2, handletextpad=0.4, columnspacing=1.0)

# ── Save ──────────────────────────────────────────────────────────────────────
graphs_dir = os.path.join(ROOT_DIR, 'graphs')
os.makedirs(graphs_dir, exist_ok=True)
fig.savefig(os.path.join(graphs_dir, 'figure2_primary.png'),
            dpi=300, bbox_inches='tight', pad_inches=0.05)
fig.savefig(os.path.join(graphs_dir, 'figure2_primary.pdf'),
            bbox_inches='tight', pad_inches=0.05)
print('Saved: graphs/figure2_primary.png and .pdf')
